#!/usr/bin/env python3
"""Tests for xenia_dump.py (Microwave XT single-dump writer + injectable morphs).

Covers the dump writer (265-byte framing invariants, checksum recomputation,
round-trip -- only intended offsets differ, name encoding, override
validation by name and index), the shipped offset map (85 injective entries,
anchor offsets), the SMF/raw sysex bank decoder, CLI dump-writer mode
(round-trip vs the library, error paths), the full-corpus MAPPING FIXTURE
every sidecar param value byte-matched against an independent strict
re-parse; checksum + anchor empirics, and the committed deliverable
(xenia_morphs_injectable.json: schema, 5 pairs x 4 steps reused verbatim
from xenia_morphs.json, per-step 265-int sysex re-derived independently
from the byte-verified parent dumps).  Also pins the md5 of the neighbor
artifacts this change must not touch.

Run::

    PYTHONPATH=/tmp/hdawpylib python3 -m pytest timbre-lib/test_xenia_dump.py -q
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys

import pytest

import xenia_dump as xd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TOOL = os.path.join(os.path.dirname(os.path.abspath(xd.__file__)),
                    "xenia_dump.py")
MD_REL = os.path.join("timbre-lib", "matrix_presets", "xenia-offset-map.md")
SHEET_REL = os.path.join("timbre-lib", "matrix_presets", "xenia.json")
MORPHS_IN_REL = os.path.join("timbre-lib", "matrix_presets",
                             "xenia_morphs.json")
MORPHS_OUT_REL = os.path.join("timbre-lib", "matrix_presets",
                              "xenia_morphs_injectable.json")
BANK_ROOT = xd.DEFAULT_BANK_ROOT

# neighbor artifacts pinned at their current digests.  xenia.json and
# xenia_morphs.json were REGENERATED by the 2026-09-18 .mid off-by-2 fix
# (harvest key space: param N lives at mid key N+2 -- xenia-offset-map.md)
# and re-pinned at the corrected digests; vavra/je8086 stay untouched.
PINNED_MD5 = {
    "timbre-lib/matrix_presets/xenia_morphs.json":
        "92279534e3816bc123e45530151b486f",
    "timbre-lib/matrix_presets/xenia.json":
        "3129622d5767f1232d24c980c2d41d2c",
    "timbre-lib/matrix_presets/vavra_morphs.json":
        "f69fbb66c2e07cd7771aca5c81ffc72b",
    "timbre-lib/matrix_presets/je8086_morphs.json":
        "9839eac0ac7cccdce5a18f9f4109fbc9",
}

MAP_ANCHORS = {
    35: "W1EnvAmount", 56: "MixRingMod", 69: "F1Cutoff", 70: "F1Resonance",
    73: "F1EnvAmount", 83: "EffectType", 88: "DelayTime",
    89: "ChorusEnabled", 90: "EffectParamB", 91: "Pan", 92: "PanKeytrack",
    93: "EffectParamC", 119: "DePan", 168: "Lfo1Delay", 175: "Lfo2Delay",
    181: "ModDelaySource", 182: "ModDelayTime", 185: "Mod1Type",
    198: "Mod4Parameter", 199: "Slot1Source", 200: "Slot1Amount",
    201: "Slot1Destination", 244: "Slot16Source", 245: "Slot16Amount",
    246: "Slot16Destination",
}


def render_json(doc):
    return json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=True) + chr(10)


def _run_cli(args, cwd=None):
    return subprocess.run([sys.executable, TOOL] + list(args),
                          capture_output=True, text=True, cwd=cwd)


# ---------------------------------------------------------------------------
# Synthetic dumps / banks
# ---------------------------------------------------------------------------

def mk_dump(name="Original Name", device=0x00, bank=0x00, program=0x07):
    dump = bytearray(xd.DUMP_LEN)
    for idx in range(xd.PARAM_INDEX_LAST + 1):
        dump[xd.IDX_PARAM_FIRST + idx] = (idx * 7) % 128
    dump[xd.IDX_NAME:xd.IDX_NAME + xd.NAME_LEN] = \
        name.encode("latin-1").ljust(xd.NAME_LEN, b" ")
    dump[xd.IDX_F0] = 0xF0
    dump[xd.IDX_ID_WALDORF] = 0x3E
    dump[xd.IDX_ID_MACHINE] = 0x0E
    dump[xd.IDX_DEVICE] = device
    dump[xd.IDX_CMD] = 0x10
    dump[xd.IDX_BANK] = bank
    dump[xd.IDX_PROGRAM] = program
    dump[xd.IDX_END] = 0xF7
    dump[xd.IDX_CHECKSUM] = xd.compute_checksum(dump)
    return bytes(dump)


def _varlen(value):
    out = bytearray([value & 0x7F])
    value >>= 7
    while value:
        out.insert(0, 0x80 | (value & 0x7F))
        value >>= 7
    return bytes(out)


def mk_smf_bank(dumps, extra_multi=True):
    """SMF bytes wrapping the dumps as F0 events (+ one MultiDump decoy)."""
    events = bytearray()
    if extra_multi:
        multi = bytearray(mk_dump())
        multi[xd.IDX_CMD] = 0x11
        multi[xd.IDX_NAME:xd.IDX_NAME + 16] = b"MultiDecoy      "
        multi[xd.IDX_CHECKSUM] = xd.compute_checksum(multi)
        events += b"\x00\xf0" + _varlen(len(multi) - 1) + multi[1:]
    for d in dumps:
        events += b"\x00\xf0" + _varlen(len(d) - 1) + d[1:]
    track = b"MTrk" + len(events).to_bytes(4, "big") + bytes(events)
    header = b"MThd" + (6).to_bytes(4, "big") + (0).to_bytes(2, "big") \
        + (1).to_bytes(2, "big") + (96).to_bytes(2, "big")
    return header + track


# ---------------------------------------------------------------------------
# Dump writer
# ---------------------------------------------------------------------------

def test_build_single_dump_framing_and_checksum():
    base = {i: (i * 3) % 128 for i in range(240)}
    dump = xd.build_single_dump(base, {}, name="P")
    assert len(dump) == 265
    assert dump[0] == 0xF0 and dump[1] == 0x3E and dump[2] == 0x0E
    assert dump[3] == 0x00 and dump[4] == 0x10
    assert dump[5] == 0x00 and dump[6] == 0x00 and dump[264] == 0xF7
    assert dump[263] == xd.compute_checksum(dump)
    assert sum(dump[7:263]) % 128 == dump[263]
    assert dump[247:263] == b"P".ljust(16, b" ")
    for idx in range(240):
        assert dump[7 + idx] == (idx * 3) % 128


def test_build_single_dump_overrides_by_name_and_index_only_intended_differ():
    base = {i: (i * 7) % 128 for i in range(240)}
    dump = xd.build_single_dump(base, {"EffectType": 5, 62: 99}, name="X")
    ref = xd.build_single_dump(base, {}, name="X")
    diffs = [i for i in range(265) if dump[i] != ref[i]]
    assert diffs == [69, 83, 263]           # F1Cutoff@69, EffectType@83
    assert dump[83] == 5 and dump[69] == 99
    assert dump[263] == xd.compute_checksum(dump)


def test_build_single_dump_name_encoding():
    base = {0: 1}
    dump = xd.build_single_dump(base, {}, name="1234567890123456789")
    assert dump[247:263] == b"1234567890123456"
    dump = xd.build_single_dump(base, {}, name="ab")
    assert dump[247:263] == b"ab".ljust(16, b" ")
    with pytest.raises(xd.DumpError):
        xd.build_single_dump(base, {}, name="\u20ac")   # not latin-1


def test_build_single_dump_validation():
    with pytest.raises(xd.DumpError):
        xd.build_single_dump({0: 128}, {})
    with pytest.raises(xd.DumpError):
        xd.build_single_dump({240: 0}, {})          # name bytes are param 240+
    with pytest.raises(xd.DumpError):
        xd.build_single_dump({0: 1}, {"Nope": 3})   # unknown name
    with pytest.raises(xd.DumpError):
        xd.build_single_dump({0: 1}, {"EffectType": 128})
    with pytest.raises(xd.DumpError):
        xd.build_single_dump({0: 1}, {}, device=128)


def test_patch_dump_preserves_header_and_recomputes_checksum():
    base = mk_dump(device=3, bank=0x20, program=9, name="Parent Patch")
    out = xd.patch_dump(base, {"F1Cutoff": 123})
    diffs = [i for i in range(265) if out[i] != base[i]]
    assert diffs == [69, 263]
    assert out[3] == 3 and out[5] == 0x20 and out[6] == 9
    assert out[247:263] == base[247:263]
    assert out[263] == xd.compute_checksum(out)


def test_load_dump_rejects_bad_input(tmp_path):
    good = mk_dump()
    p = tmp_path / "ok.syx"
    p.write_bytes(good)
    assert xd.load_dump(str(p)) == good
    mutators = (lambda d: d[:-1],
                lambda d: b"\xf1" + d[1:],
                lambda d: d[:-1] + b"\x00",
                lambda d: d[:4] + b"\x11" + d[5:])
    for i, mutator in enumerate(mutators):
        bad = tmp_path / ("bad%d.syx" % i)
        bad.write_bytes(mutator(good))
        with pytest.raises(xd.DumpError):
            xd.load_dump(str(bad))


def test_offset_map_contract():
    mapping = xd.load_offset_map()
    assert len(mapping) == 85
    assert len(set(mapping.values())) == len(mapping)      # injective
    assert all(xd.IDX_PARAM_FIRST <= off <= xd.IDX_PARAM_LAST
               for off in mapping)
    for off, name in MAP_ANCHORS.items():
        assert mapping.get(off) == name, (off, name)
    assert "EffectParamA" not in mapping.values()          # aliased to DelayTime


def test_md_documents_rule_and_citations():
    with open(os.path.join(REPO, MD_REL), encoding="utf-8") as fh:
        md = fh.read()
    for marker in ("dump_byte_offset = 7 + linear_json_index",
                   "xtMidiTypes.h:62-65", "xtState.h:67",
                   "wState.h:18-24", "parameterdescriptions.cpp:348-356",
                   "g_singleNamePosition =", "sum(full[7:263]) & 0x7F",
                   "1,166,386", "mismatches"):
        assert marker in md, marker


# ---------------------------------------------------------------------------
# Bank decoding
# ---------------------------------------------------------------------------

def test_load_bank_mid_smf_with_multi_decoy(tmp_path):
    d1 = mk_dump(name="Alpha Patch")
    d2 = mk_dump(name="Beta Patch", bank=1, program=2)
    path = tmp_path / "bank.mid"
    path.write_bytes(mk_smf_bank([d1, d2]))
    rows = xd.load_bank(str(path))
    assert [r["name"] for r in rows] == ["Alpha Patch", "Beta Patch"]
    assert all(r["container"] == "mid" for r in rows)
    assert rows[0]["dump"] == d1 and rows[1]["dump"] == d2


def test_load_bank_raw_sysex_stream(tmp_path):
    d1, d2 = mk_dump(name="Raw One"), mk_dump(name="Raw Two")
    path = tmp_path / "bank.syx"
    path.write_bytes(d1 + d2)
    rows = xd.load_bank(str(path))
    assert [r["name"] for r in rows] == ["Raw One", "Raw Two"]


def test_load_bank_usb_record_synthesizes_framing(tmp_path):
    rec = bytearray(256)
    for i in range(240):
        rec[i] = (i * 5) % 128
    rec[240:256] = b"Usb Test Patch01"
    path = tmp_path / "bank.usb"
    path.write_bytes(bytes(rec) * 2)
    rows = xd.load_bank(str(path))
    assert len(rows) == 2 and rows[0]["container"] == "usb"
    assert rows[0]["name"] == "Usb Test Patch01"
    assert rows[0]["params"][0] == 0 and rows[0]["params"][10] == 50
    dump = rows[0]["dump"]
    assert len(dump) == 265 and dump[0] == 0xF0 and dump[264] == 0xF7
    assert dump[4] == 0x10
    for i in range(240):
        assert dump[7 + i] == rec[i]
    assert dump[263] == xd.compute_checksum(dump)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def test_cli_round_trip_and_errors(tmp_path):
    d1 = mk_dump(name="Cli Base", bank=1)
    bank = tmp_path / "b.mid"
    bank.write_bytes(mk_smf_bank([d1]))
    out = tmp_path / "out.syx"
    proc = _run_cli(["--base-bank", str(bank), "--patch", "Cli Base",
                     "--set", "EffectType=5,F1Cutoff=90", "--name", "Cli New",
                     "--bank", "1", "--out", str(out)])
    assert proc.returncode == 0, proc.stderr
    expected = xd.build_single_dump(
        {i: d1[7 + i] for i in range(240)},
        {"EffectType": 5, "F1Cutoff": 90}, name="Cli New", bank=1)
    assert out.read_bytes() == expected
    proc = _run_cli(["--base-bank", str(bank), "--patch", "Nope",
                     "--out", str(out)])
    assert proc.returncode == 2 and "not found" in proc.stderr
    proc = _run_cli(["--base-bank", str(bank), "--patch", "Cli Base",
                     "--set", "EffectType=x", "--out", str(out)])
    assert proc.returncode == 2
    proc = _run_cli(["--base-bank", str(bank)])
    assert proc.returncode == 2


def test_cli_list_patches(tmp_path):
    bank = tmp_path / "b.mid"
    bank.write_bytes(mk_smf_bank([mk_dump(name="One"), mk_dump(name="Two")]))
    proc = _run_cli(["--base-bank", str(bank), "--list-patches"])
    assert proc.returncode == 0
    assert "One" in proc.stdout and "Two" in proc.stdout


# ---------------------------------------------------------------------------
# Full-corpus mapping fixture (the STOP-GATE, kept executable)
# ---------------------------------------------------------------------------

def _sidecar_banks():
    out = []
    for dirpath, dirnames, filenames in os.walk(BANK_ROOT):
        dirnames.sort()
        for fn in sorted(filenames):
            if fn.endswith(".xenia.json"):
                out.append(os.path.join(dirpath, fn))
    return sorted(out)


def test_corpus_sidecars_exist():
    if not os.path.isdir(BANK_ROOT):
        pytest.skip("microwave bank corpus not mounted")
    assert len(_sidecar_banks()) == 34


def test_mapping_fixture_byte_match_all_sidecars():
    if not os.path.isdir(BANK_ROOT):
        pytest.skip("microwave bank corpus not mounted")
    total = 0
    for sc_path in _sidecar_banks():
        bank_path = sc_path[: -len(".xenia.json")]
        with open(sc_path, encoding="utf-8") as fh:
            sc = json.load(fh)
        rows = xd.load_bank(bank_path)
        fmap = {r["name"]: r["dump"] for r in rows}
        container = rows[0]["container"] if rows else None
        for name, kv in sc.get("params", {}).items():
            if name not in fmap:
                continue                      # name-edge cases (see .md)
            dump = fmap[name]
            for k, v in kv.items():
                pos = (7 if container == "usb" else 5) + int(k)
                assert dump[pos] == v, (bank_path, name, k, pos)
                total += 1
    assert total > 1_000_000


def test_corpus_checksum_and_anchor_bytes():
    if not os.path.isdir(BANK_ROOT):
        pytest.skip("microwave bank corpus not mounted")
    dumps = checksum_ok = version1 = 0
    for sc_path in _sidecar_banks():
        bank_path = sc_path[: -len(".xenia.json")]
        if os.path.splitext(bank_path)[1].lower() in (".usb", "\u00b5sb"):
            continue                          # framing synthesized, not real
        for row in xd.load_bank(bank_path):
            dump = row["dump"]
            dumps += 1
            assert dump[0] == 0xF0 and dump[264] == 0xF7
            assert (dump[1], dump[2], dump[4]) == (0x3E, 0x0E, 0x10)
            if xd.compute_checksum(dump) == dump[263]:
                checksum_ok += 1
            if dump[7] == 1:
                version1 += 1
    assert dumps > 3000
    assert checksum_ok == dumps               # formula holds for every dump
    assert version1 >= dumps - 4              # Version param (index 0) == 1


def _refind_parent_dump(resolution, preset):
    """Re-find the byte-verified parent dump named in baseResolution."""
    named = xd._named_values(preset, xd.name_to_offset())
    shift = -2 if resolution["how"] == "vocab-shifted" else 0
    for path in xd._bank_files(BANK_ROOT):
        if os.path.basename(path) != resolution["bank"]:
            continue
        for row in xd.load_bank(path):
            if row["name"] != resolution["patch"]:
                continue
            if row["container"] != resolution["container"]:
                continue
            if xd._matches(row["dump"], named, shift) == len(named):
                return row["dump"]
    raise AssertionError("baseResolution dump not re-findable: %r"
                         % (resolution,))


def test_injectable_morphs_deliverable():
    if not os.path.isdir(BANK_ROOT):
        pytest.skip("microwave bank corpus not mounted")
    with open(os.path.join(REPO, MORPHS_OUT_REL), encoding="utf-8") as fh:
        text = fh.read()
    doc = json.loads(text)
    assert doc["schema"] == "hdaw.matrix.preset.morph.v1"
    assert doc["sourceSheet"] == SHEET_REL.replace(os.sep, "/")
    assert doc["derivedFrom"] == MORPHS_IN_REL.replace(os.sep, "/")
    assert doc["sysexRoots"] == ["microwave"]
    assert doc["unverified"] is True
    for marker in ("/mnt/", "D:/pdf", ":/pdf"):
        assert marker not in text
    with open(os.path.join(REPO, MORPHS_IN_REL), encoding="utf-8") as fh:
        morphs = json.load(fh)
    with open(os.path.join(REPO, SHEET_REL), encoding="utf-8") as fh:
        sheet = json.load(fh)
    by_id = {p["id"]: p for p in sheet["presets"]}
    assert [p["pair"] for p in doc["pairs"]] == \
        [p["pair"] for p in morphs["pairs"]]
    name_to_off = xd.name_to_offset()
    for pair in doc["pairs"]:
        res = pair["baseResolution"]
        assert res["how"] in ("verified", "vocab-shifted")
        # per-pair provenance (off-by-2 fix): .usb parents resolve under the
        # direct labeling, .mid parents under the corrected shifted-back
        # labeling -- both byte-verify at dump offset 7+index
        assert res["provenance"] == ("verified"
                                     if res["container"] == "usb"
                                     else "mid-corrected")
        assert res["byteMatches"] >= xd.MIN_PARENT_CHECKS
        parent = by_id[pair["parents"][0]["id"]]
        base = _refind_parent_dump(res, parent)
        shift = -2 if res["how"] == "vocab-shifted" else 0
        assert len(pair["steps"]) == 4
        for step in pair["steps"]:
            sysex = step["sysex"]
            assert len(sysex) == 265
            assert sysex[0] == 0xF0 and sysex[264] == 0xF7
            assert (sysex[1], sysex[2], sysex[4]) == (0x3E, 0x0E, 0x10)
            assert sysex[5] == 0x20     # single edit buffer (live-verified)
            assert sysex[263] == xd.compute_checksum(sysex)
            # independent re-derivation: parent bytes + mapped step values
            expected = bytearray(base)
            expected[5] = 0x20          # delivery bank byte (outside cksum)
            touched = {5}
            for name, value in sorted(step["preset"]["params"].items()):
                if value is None or name not in name_to_off:
                    continue
                pos = name_to_off[name] + shift
                expected[pos] = int(round(value)) \
                    if isinstance(value, float) else value
                touched.add(pos)
            expected[263] = xd.compute_checksum(expected)
            diff_ix = [i for i in range(265) if list(expected)[i] != sysex[i]][:8]
            assert list(expected) == sysex, (pair['pair'], step['step'], diff_ix)
            assert touched - {5}                    # at least one param write
            for i in range(265):                    # nothing else moved
                if i not in touched and i != 263:
                    assert sysex[i] == base[i]


def test_injectable_morphs_rebuild_byte_stable():
    if not os.path.isdir(BANK_ROOT):
        pytest.skip("microwave bank corpus not mounted")
    doc = xd.build_injectable_morphs(
        os.path.join(REPO, MORPHS_IN_REL), BANK_ROOT)
    # the committed deliverable carries the two documented post-processing
    # steps of the off-by-2 regeneration (xenia-offset-map.md, "Morph
    # injectability"): every step's SysEx is stamped with the single-edit-
    # buffer bank byte 0x20 (byte 5, outside the checksum range; verified
    # audible live 2026-09-16), and each pair records per-parent provenance
    # ("verified" for .usb banks, "mid-corrected" for .mid banks).
    for pair in doc["pairs"]:
        pair["baseResolution"]["provenance"] = (
            "verified" if pair["baseResolution"]["container"] == "usb"
            else "mid-corrected")
        for step in pair["steps"]:
            sysex = list(step["sysex"])
            sysex[5] = 0x20
            step["sysex"] = sysex
    with open(os.path.join(REPO, MORPHS_OUT_REL), "rb") as fh:
        assert fh.read() == render_json(doc).encode("utf-8")


# ---------------------------------------------------------------------------
# Neighbor-artifact pins
# ---------------------------------------------------------------------------

def test_committed_neighbor_artifacts_untouched():
    for rel, digest in PINNED_MD5.items():
        path = os.path.join(REPO, rel)
        assert os.path.isfile(path), rel
        with open(path, "rb") as fh:
            assert hashlib.md5(fh.read()).hexdigest() == digest, rel
