// McpTools_Device.cpp — core-synth device parameter map MCP tool.
//
// list_device_params — read-only introspection of the per-engine Device
// Parameter Map (timbre-lib/device_map/<engine>.params.json, schema
// hdaw.device.param.map.v1), generated by timbre-lib/build_device_map.py from
// the harvested matrix corpus + name grammar. It answers the agent question
// that list_fx_params cannot: "what on this device can do <intent>, and how do
// I reach it?".
//
// The loader lives in src/common/DeviceParamMap.{h,cpp} so the RPC surface
// (frontend/router/Router_Device.cpp, device.listParams) serves the identical
// artifact with identical filtering — RPC/MCP parity by construction (AGENTS.md
// "MCP feature parity" + "RPC parity").
//
// Engine surface ONLY: file reads. No DSP, no audio-thread code, no ValueTree,
// no plugin instantiation, no RPC mutations.
//
// Location: env HDAW_DEVICE_MAP_DIR first, else <cwd>/timbre-lib/device_map,
// <exeDir>/../timbre-lib/device_map, <exeDir>/timbre-lib/device_map. The
// resolved dir is cached, keyed on the env value (so tests re-resolve).
//
// Plan: docs/plans/2026-09-21-device-param-map.md

#include "McpTools.h"
#include "McpTools_Private.h"
#include "McpServer.h"
#include "McpToolDef.h"
#include "../engine/AudioEngine.h"
#include "../common/DeviceParamMap.h"

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QString>

namespace mcp {

namespace {

constexpr int kDefaultLimit = 100;
constexpr int kMaxLimit = 1000;

QString textResult(const QJsonObject& o)
{
    return QString::fromUtf8(QJsonDocument(o).toJson(QJsonDocument::Compact));
}

} // namespace

void registerDeviceTools(McpServer& s, AudioEngine* e)
{
    (void)e; // the device map is file-backed; no engine state is read

    s.registerTool({ "list_device_params",
        "List a core-synth device's parameters by MUSICAL INTENT, from the"
        " per-engine Device Parameter Map (timbre-lib/device_map/, generated by"
        " timbre-lib/build_device_map.py; HDAW_DEVICE_MAP_DIR overrides the"
        " location). Answers 'what on this engine can do X, and is it reachable'"
        " — which list_fx_params (a raw N-entry dump) cannot. Omit `engine` for"
        " the index: available engines + the intent vocabulary + stage ownership."
        " With `engine`, returns filtered params: {engine, appliesVia,"
        " durability, durabilityNote, counts, matched, params:[{name,category,"
        "tier,intents,stages,index?,offset?,trapReason?,note?}]}. tier is"
        " identity | movement | trap; trapReason names WHY a param is unusable"
        " (bit-alias, unmatched-index, unnamed-dump-field, unclassified)."
        " Audibility is not yet probed (slice 2) — do not read absence of a trap"
        " as proof a param is audible/durable; check `durability`.",
        objSchema({ { "engine",   QJsonObject{ { "type", "string" } } },
                    { "category", QJsonObject{ { "type", "string" } } },
                    { "intent",   QJsonObject{ { "type", "string" } } },
                    { "stage",    QJsonObject{ { "type", "string" } } },
                    { "tier",     QJsonObject{ { "type", "string" } } },
                    { "limit",    QJsonObject{ { "type", "integer" } } } }),
        "fx",
        [](const QJsonObject& a) -> McpToolResult {
            const auto& dd = HDAW::resolveDeviceMapDir();
            if (dd.dir.isEmpty())
                return McpToolResult::text(dd.error, true);

            const QString engine = a.value("engine").toString();

            // -- index mode: engines + intent vocabulary + stage ownership ------
            if (engine.isEmpty())
            {
                QString err;
                const QJsonObject root = HDAW::readDeviceMapFile(dd.dir + "/index.json", err);
                if (!err.isEmpty())
                    return McpToolResult::text(
                        QString("device map index unavailable: %1").arg(err), true);
                const QString schema = root.value("schema").toString();
                if (schema != HDAW::kDeviceIndexSchema)
                    return McpToolResult::text(
                        QString("index.json: unsupported schema '%1' (expected %2)")
                            .arg(schema, HDAW::kDeviceIndexSchema), true);
                QJsonObject out = root;
                out["dir"] = dd.dir;
                return McpToolResult::text(textResult(out));
            }

            // -- engine mode: filtered params ----------------------------------
            if (!HDAW::validEngineId(engine))
                return McpToolResult::text(
                    "engine must match [a-z0-9_] (e.g. je8086, virus, nodalred2x, xenia, vavra)",
                    true);

            QString err;
            const QJsonObject root =
                HDAW::readDeviceMapFile(dd.dir + "/" + engine + ".params.json", err);
            if (!err.isEmpty())
                return McpToolResult::text(
                    QString("%1: %2 (available: %3)")
                        .arg(engine, err, HDAW::deviceMapEngines(dd.dir).join(", ")), true);
            const QString schema = root.value("schema").toString();
            if (schema != HDAW::kDeviceMapSchema)
                return McpToolResult::text(
                    QString("%1.params.json: unsupported schema '%2' (expected %3)")
                        .arg(engine, schema, HDAW::kDeviceMapSchema), true);

            const QString fCategory = a.value("category").toString();
            const QString fIntent   = a.value("intent").toString();
            const QString fStage    = a.value("stage").toString();
            const QString fTier     = a.value("tier").toString();
            int limit = a.value("limit").toInt(kDefaultLimit);
            if (limit <= 0) limit = kDefaultLimit;
            if (limit > kMaxLimit) limit = kMaxLimit;

            // Fail loudly on a filter that matches nothing, rather than
            // returning an empty list the agent might read as "device has none".
            int matched = 0;
            const QJsonArray params = HDAW::filterDeviceParams(
                root, fCategory, fIntent, fStage, fTier, limit, matched);

            QJsonObject out {
                { "engine", engine },
                { "dir", dd.dir },
                { "appliesVia", root.value("appliesVia") },
                { "durability", root.value("durability") },
                { "durabilityNote", root.value("durabilityNote") },
                { "counts", root.value("counts") },
                { "matched", matched },
                { "returned", params.size() },
                { "truncated", matched > params.size() },
                { "params", params } };
            if (matched == 0)
            {
                out["hint"] = "no params matched these filters; omit filters (or use"
                              " the index mode) to see the engine's full map";
            }
            return McpToolResult::text(textResult(out));
        } });
}

} // namespace mcp
